apiVersion: v1
kind: Namespace
metadata:
  name: devops-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab
  namespace: devops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-lab
  template:
    metadata:
      labels:
        app: devops-lab
    spec:
      containers:
        - name: app
          image: devops-lab:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: devops-lab
  namespace: devops-lab
spec:
  type: ClusterIP
  selector:
    app: devops-lab
  ports:
    - name: http
      port: 80
      targetPort: http
