apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vrivas99/devops-lab.git
    targetRevision: main
    path: helm/devops-lab
    helm:
      releaseName: devops-lab
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-lab
